/**
 * The privacy guard: this repository is public, so no file may carry the
 * product's private details (decision numbers, plan sections, database
 * internals, the private repository's name, people's real names or
 * addresses, private hostnames, the product team's own project key).
 *
 *   npm run privacy        scan every file git knows (tracked or new, not ignored)
 *
 * test/privacy.test.ts runs the same scan, and checks every rule against
 * its own examples. To extend the guard, add a rule to RULES (with an
 * example it must catch and one it must not), or an entry to the allow
 * lists below. Patterns are written so that this file doesn't match itself
 * (for example `K[e]lly`), and the examples are assembled from pieces.
 */
import { execFileSync } from 'node:child_process';
import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

export interface Rule {
  id: string;
  /** What the rule keeps out, for the report. */
  why: string;
  /** Global regular expression; every match is a finding unless allowed. */
  pattern: RegExp;
  /** Matches that are fine in some files: the file path and the text around the match. */
  allow?: { path: RegExp; text: RegExp }[];
  /** Further check of a match: return false to let it pass. */
  forbidden?: (match: RegExpExecArray) => boolean;
  /** Texts the rule must catch, and texts it must let pass (the self-test). */
  examples: { hit: string[]; miss?: string[] };
}

/** Files never scanned (third-party or generated by npm). */
export const EXCLUDED: RegExp[] = [/^package-lock\.json$/, /(^|\/)node_modules\//, /^dist\//];

/** Email domains for made-up people. */
export const ALLOWED_EMAIL_DOMAINS = ['example.com', 'example.org', 'example.net'];

/** Public addresses that may appear: the security contact and the commit trailer. */
export const ALLOWED_EMAILS = ['security@buildit.social', 'noreply@anthropic.com'];

/** buildIt.Social hostnames that are public. Any other *.buildit.social host is private. */
export const ALLOWED_HOSTS = ['api.buildit.social', 'www.buildit.social'];

const j = (...parts: string[]): string => parts.join('');

export const RULES: Rule[] = [
  {
    id: 'decision-number',
    why: 'internal decision numbers',
    pattern: /\bD-\d+\b/g,
    examples: { hit: [j('D', '-58'), j('see D', '-8 amended')] },
  },
  {
    id: 'plan-section',
    why: 'references to sections of internal plans',
    pattern: new RegExp(String.fromCharCode(0xa7), 'g'),
    examples: { hit: [j(String.fromCharCode(0xa7), '8.3')], miss: ['section 8'] },
  },
  {
    id: 'sql-file',
    why: 'database migration files',
    pattern: /\.s[q]l\b/gi,
    examples: { hit: [j('20261105_init', '.s', 'ql')], miss: ['SQLite', 'the sequel'] },
  },
  {
    id: 'backend-vendor',
    why: 'the backend platform behind the API',
    pattern: /supa[b]ase/gi,
    examples: { hit: [j('supa', 'base/functions'), j('Supa', 'base')], miss: ['superbase'] },
  },
  {
    id: 'schema-change-files',
    why: 'the database schema history',
    pattern: /\bmigr[a]tions\b/gi,
    examples: { hit: [j('the migr', 'ations folder')], miss: ['migrating birds'] },
  },
  {
    id: 'row-level-security',
    why: 'database row-level security',
    pattern: /\bR[L]S\b/g,
    examples: { hit: [j('R', 'LS policies')], miss: ['URLSearchParams', 'TLS'] },
  },
  {
    id: 'database-rest-layer',
    why: 'the database REST layer',
    pattern: /postg[r]est/gi,
    examples: { hit: [j('Postg', 'REST')], miss: ['postgate'] },
  },
  {
    id: 'database-test-tooling',
    why: 'database test tooling',
    pattern: /\bpg[T]AP\b/gi,
    examples: { hit: [j('pg', 'TAP tests')], miss: ['pgtapir'] },
  },
  {
    id: 'database-engine',
    why: 'database internals',
    pattern: /\bpostg[r]es(?:ql)?\b/gi,
    examples: { hit: [j('Postg', 'res 17'), j('postg', 'resql')], miss: ['postgrad'] },
  },
  {
    id: 'jwt',
    why: 'token internals of the backend',
    pattern: /\bJ[W]T\b/g,
    examples: { hit: [j('the J', 'WT secret')], miss: ['JWTS-like', 'jwt'] },
  },
  {
    id: 'owner-first-name',
    why: "the owner's name",
    pattern: /\bK[e]lly\b/gi,
    examples: { hit: [j('K', 'elly'), j('k', 'elly@')], miss: ['Kellyanne'] },
  },
  {
    id: 'owner-last-name',
    why: "the owner's name (the company name is the copyright holder)",
    pattern: /\bK[a]mm\b/gi,
    allow: [{ path: /^(LICENSE|package\.json)$/, text: /K[a]mm Creative Solutions/ }],
    examples: { hit: [j('K', 'amm Corp')], miss: ['github.com/kammcs/buildit-mcp'] },
  },
  {
    id: 'private-repo',
    why: "the product's private repository",
    pattern: /buildit-s[o]cial/gi,
    examples: { hit: [j('kammcs/buildit', '-social')], miss: ['buildit-mcp', 'buildIt.Social'] },
  },
  {
    id: 'project-key',
    why: "the product team's own project key (use DEMO)",
    pattern: /\bB[I]S\b/g,
    examples: { hit: [j('B', 'IS-42'), j('project B', 'IS')], miss: ['BISON', 'ABIS', 'bis'] },
  },
  {
    id: 'email',
    why: 'real email addresses (use example.com)',
    pattern: /[A-Za-z0-9._%+-]+@((?:[A-Za-z0-9-]+\.)+[A-Za-z]{2,})\b/g,
    forbidden: (m) => {
      const address = m[0].toLowerCase();
      const domain = (m[1] ?? '').toLowerCase();
      if (ALLOWED_EMAILS.includes(address)) return false;
      return !ALLOWED_EMAIL_DOMAINS.some((d) => domain === d || domain.endsWith(`.${d}`));
    },
    examples: {
      hit: [j('ana', '@', 'acme.io'), j('Sam.Lee', '@', 'mail.example.co')],
      miss: ['ana@example.com', 'sam@team.example.org', 'security@buildit.social', 'zod@4.1.0'],
    },
  },
  {
    id: 'private-host',
    why: 'private hostnames (only the public API host may appear)',
    pattern: /\b((?:[a-z0-9-]+\.)+buildit\.social)\b/gi,
    forbidden: (m) => !ALLOWED_HOSTS.includes((m[1] ?? '').toLowerCase()),
    examples: {
      hit: [
        j('https://api', '-dev', '.buildit.social'),
        j('dev', '.buildit.social'),
        j('a.b', '.buildit.social'),
      ],
      miss: [
        'https://api.buildit.social/functions/v1/agent-api',
        'https://buildit.social',
        'security@buildit.social',
      ],
    },
  },
];

export interface Finding {
  file: string;
  line: number;
  rule: string;
  match: string;
}

function allowed(rule: Rule, file: string, text: string, index: number): boolean {
  return (rule.allow ?? []).some((a) => {
    if (!a.path.test(file)) return false;
    const around = text.slice(Math.max(0, index - 100), index + 100);
    return a.text.test(around);
  });
}

/** The findings in one text, as if it were the file `file` (a path with forward slashes). */
export function scanText(file: string, text: string, rules: readonly Rule[] = RULES): Finding[] {
  const out: Finding[] = [];
  for (const rule of rules) {
    const pattern = new RegExp(rule.pattern.source, rule.pattern.flags);
    for (let m = pattern.exec(text); m !== null; m = pattern.exec(text)) {
      if (m[0].length === 0) pattern.lastIndex++;
      if (rule.forbidden && !rule.forbidden(m)) continue;
      if (allowed(rule, file, text, m.index)) continue;
      const line = text.slice(0, m.index).split('\n').length;
      out.push({ file, line, rule: rule.id, match: m[0] });
    }
  }
  return out;
}

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** Every file git knows (tracked, or new and not ignored); without git, every file on disk. */
export function repoFiles(root: string = ROOT): string[] {
  let files: string[];
  try {
    files = execFileSync('git', ['ls-files', '--cached', '--others', '--exclude-standard', '-z'], {
      cwd: root,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .split('\0')
      .filter(Boolean);
  } catch {
    files = [];
    const walk = (dir: string): void => {
      for (const name of readdirSync(dir)) {
        if (name === '.git' || name === 'node_modules' || name === 'dist') continue;
        const full = join(dir, name);
        if (statSync(full).isDirectory()) walk(full);
        else files.push(relative(root, full).split(sep).join('/'));
      }
    };
    walk(root);
  }
  return [...new Set(files)].filter((f) => !EXCLUDED.some((e) => e.test(f))).sort();
}

/** Scans the repository. */
export function scanRepo(root: string = ROOT): Finding[] {
  const out: Finding[] = [];
  for (const file of repoFiles(root)) {
    let buffer: Buffer;
    try {
      buffer = readFileSync(join(root, file));
    } catch {
      continue; // deleted but not yet staged
    }
    if (buffer.includes(0)) continue; // binary
    out.push(...scanText(file, buffer.toString('utf8')));
  }
  return out;
}

/** Runs each rule on its own examples; returns what went wrong. */
export function selfTest(rules: readonly Rule[] = RULES): string[] {
  const problems: string[] = [];
  for (const rule of rules) {
    for (const hit of rule.examples.hit) {
      if (!scanText('example.md', hit, [rule]).length) problems.push(`${rule.id} misses "${hit}"`);
    }
    for (const miss of rule.examples.miss ?? []) {
      if (scanText('example.md', miss, [rule]).length) problems.push(`${rule.id} flags "${miss}"`);
    }
  }
  return problems;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const problems = selfTest();
  const findings = scanRepo();
  for (const p of problems) console.error(`self-test: ${p}`);
  for (const f of findings) {
    const why = RULES.find((r) => r.id === f.rule)?.why ?? '';
    console.error(`${f.file}:${f.line}: ${f.rule} (${why}): ${f.match}`);
  }
  if (problems.length + findings.length > 0) {
    console.error(
      `Privacy guard: ${findings.length} finding(s), ${problems.length} self-test problem(s).`,
    );
    process.exit(1);
  }
  console.log(`Privacy guard: ${repoFiles().length} files clean.`);
}
